
version: '3'
services:
    sqlserver:
      container_name: webMethods105_db
      image: webmethods105_db:v5
      hostname: webmethods
      ports:
        - "1433:1433"
      environment:
        - SA_PASSWORD=Manage100!
        - ACCEPT_EULA=--accept-eula
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      volumes:
        - c:/Docker/volumes/share:/share
        
    wm:
      container_name: webMethods105
      image: webmethods105:v5
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      hostname: webmethods
      ports:
        - "5555:5555"
        - "9999:9999"
        - "9100:9100"
        - "1212:1212"
        - "1414:1414"
        - "7001:7001"
        - "7002:7002"
        - "9011:9000"
        - "8585:8585"
        - "12503:12503"
        - "15000:15000"
        - "7011:7011"
        - "7012:7012"
        - "15001:15001"
        - "1515:1515"
        - "15005:15005"
        - "6666:6666"
        - "1026:1026"
        - "1027:1027"
      environment:
        - INSTANCE_NAME=default
        - JAVA_HOME=/opt/softwareag/jvm/jvm
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - LD_LIBRARY_PATH=/opt/softwareag/IntegrationServer/instances/default/lib/jars/
      volumes:
        - /Users/julien/Documents/Docker/Docker_Data-Shared:/opt/shared
      depends_on:
        - "sqlserver"
      links:
        - "sqlserver"

    mashzone:
      container_name: webMethods105_mz
      image: webmethods105_mz:v5
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      hostname: webmethods
      ports: 
        - "8080:8080"
        - "7021:7021"
        - "7022:7022"
      environment:
        - JAVA_HOME=/opt/softwareag/jvm/jvm
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      volumes:
        - /Users/julien/Documents/Docker/Docker_Data-Shared:/opt/shared
      depends_on:
        - "sqlserver"
      links:
        - "sqlserver"
        - "wm"

